---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUD0g6hOH8q29FwJf5EA6x6bdEH3gwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkxMTIwMTU0MjAwWhcNMjQxMTE4MTU0MjAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AKuupCrUawRaY23Y6Cgvamk2aYx45EXMO7ZrnnEdqqzQx1qXtPCRC1cT4Uf62uEa
    ps6cRdtNfLF7PiQFd9/5U8Uk1m1Cgn+WXmalFOIZEVDIc3TvzvXV7YDn8iM+Kxtd
    9IDaoNhuc1AC61pAkL5Zw88/Syv4O4bQUCMKslHVzYZsxb5DbOhAKW+pBYGJO6Kl
    L1V/YXPB7i/EMUrPOd7genypxOPDqC24W6iy9LNKluGvgVngo1wjGZaTd1UZBgKp
    vvdKQw8EC9Zcj5YGqarucvSVSvwAEmxDhKKOs6//TnK1xDfl2fV4Z8LQBKLlRMPo
    S1AEX5LH5IsIA8Zpo6wZPr/PL9WRbuj9kfYfm0lPMbZHTGrN3HyLAazuMGSqV1iR
    aa4xjO1tSS/TrB+9pFq3DlzLgHhfT8trPCbMI10z9JDSPL963E1VqIXnPCwSxcIc
    5LCuufMHv/EpGkx6eKF3v07oPciPX/VNGmxna5p+8zAM/w9uEEBR9o57uAFOKjq3
    NDifjWNDUzirlrMtP7F8MdHW/rViiX6ioDNNTcPVeznCux4koIwRG3JU4+rOhwU8
    iAWsWOB9EoQLjt5w2++1ty7+dg+4JCLaqTUYJCVRuPO9RjysH8dppMvOS3aG92Rv
    e789P008DYJvpbC4oJJr1lftwlu3aAK7TIZh1uZI8T57AgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTKGAuZqSmv6aHS
    ZwLneao1h8QtezANBgkqhkiG9w0BAQ0FAAOCAgEAVAwHGsXCJGnfpIn0CyQ2XJ1e
    OLE6v28COmWVYj/tJ6Ekrwn2Q+iOFmTyBCbT01FnW6WUrJiAYOOSVjed1k5F1Qzt
    cbqWYl/Mk8M1m5dIPf6ksOjgOSb3jvbQHds2COC++jPe0xUbVMahbYVlDJZFF1Mi
    7hmbqHJN68MLMfIcaZ1wZSxlZ5a9C6wy0Nwa3oNasCsvvtusit79Te2u60DD0fqi
    ilsSgmv/nA7PEqBOjAUe7m+8GTre4anuj3jeOFtt9UJ+8/B2BDH1TycBtIHflNMB
    swXlI5qHqxnkcBWPrnzrnQ569xGcnW0DIazE4uGBJhiPFm8iQFiE5Q1inK9cBg7M
    gnSFYjceeQapMQxzThY6kLX1+JEkHQryGBX3G61WIGKtn0IycUyFciPkQqJ9HOKa
    M/Fodv8WWpN1zzrtHCn2eZ3F7tIiaFGiY3yYAp+MzdTmPQ3gqn1Go2UU1hfwfGpR
    iCEdkvIQxavEjfp0b1JhDgEui4YmnkKreaMwsymGl7V1XQ/AElG9+QFQ+xKo8zH/
    uiPCsJNCP4om3e8zRmrGVmIBNRVIwnWilsnsmfNjfAnSS8+ZKJd3f81MOvwA4aCn
    jXCkAHncqzKMmoEABbD1L/9edaNz8VaqwSHV2GTo7ILAidm9b0FsPddzKJRl9O0z
    6Om29fX2ROSvUw/iqRk=
    -----END CERTIFICATE-----
    
